### ISSUE TITLE
Problema aggiornamento

### ISSUE THREAD

**Issue by biagioDonato** [Zanzibar82/plugin.video.streamondemand#31]
Ciao a tutti,
Utilizzo Streaming on Demand come plugin di Kodi 15.2 su lubuntu 14.04 ARM
ho un problema durante l'aggiornamento dalla versione 5.1.9 alla 5.2.4
questo è il log di kodi
```
15:04:11 T:2936181792   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'zipfile.BadZipfile'>
                                            Error Contents: File is not a zip file
                                            Traceback (most recent call last):
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/default.py", line 27, in <module>
                                                launcher.run()
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/platformcode/launcher.py", line 57, in run
                                                updater.update(params)
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/updater.py", line 229, in update
                                                unzipper.extract(localfilename,destpathname)
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/ziptools.py", line 22, in extract
                                                zf = zipfile.ZipFile(file)
                                              File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
                                                self._RealGetContents()
                                              File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
                                                raise BadZipfile, "File is not a zip file"
                                            BadZipfile: File is not a zip file
                                            -->End of Python script error report<--
15:04:11 T:3036332032   ERROR: GetDirectory - Error getting plugin://plugin.video.streamondemand/?action=update&version=5.2.4
15:04:11 T:3036332032   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamondemand/?action=update&version=5.2.4) failed

```

**Comment by dentaku65** [comment]
Rimuovi SOD e installa direttamente la versione 5.2.4

**Comment by biagioDonato** [comment]
Alla fine ho fatto così
